{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.matugen;

  matugenArgs =
    if cfg.wallpaper != null then
      let
        safeWallpaperPath = builtins.unsafeDiscardStringContext "${cfg.wallpaper}";
      in
      "image \"${safeWallpaperPath}\""
    else if cfg.seedColor != null then
      "color hex \"${cfg.seedColor}\""
    else
      "";

  # We use IFD (Import From Derivation) to run matugen at evaluation time
  matugenJson = pkgs.runCommand "matugen-colors.json" { } ''
    ${pkgs.matugen}/bin/matugen ${matugenArgs} -j hex -m ${cfg.mode} -t scheme-${cfg.scheme} --prefer saturation > $out
  '';

  # Parse the generated JSON if the module is enabled
  generatedTheme =
    if (cfg.enable && matugenArgs != "") then
      builtins.fromJSON (builtins.readFile matugenJson)
    else
      {
        colors = {
          dark = { };
          light = { };
        };
      };

  # Transparently parse colors and base16, keeping dark/light/default structure
  parseColorObject =
    obj:
    if builtins.isAttrs obj && builtins.hasAttr "color" obj then
      obj.color
    else if builtins.isAttrs obj then
      builtins.mapAttrs (n: v: parseColorObject v) obj
    else
      obj;

  parsedColors = parseColorObject (generatedTheme.colors or { });
  parsedBase16 = parseColorObject (generatedTheme.base16 or { });

  # Palettes don't have dark/light variants, they are just tones
  parsedPalettes = builtins.mapAttrs (
    name: tones: builtins.mapAttrs (tone: value: value.color or "") tones
  ) (generatedTheme.palettes or { });

  # Final theme structure
  theme = {
    generated = {
      colors = parsedColors;
      base16 = parsedBase16;
      palettes = parsedPalettes;
    };
    custom = cfg.customColors;
  };
in
{
  options.matugen = {
    enable = lib.mkEnableOption "Matugen color generation module";

    wallpaper = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = "./wallpapers/image.png";
      description = ''
        Path to the wallpaper image to use as the base for the color palette.
        Mutually exclusive with `seedColor`.
      '';
    };

    seedColor = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "#ff0000";
      description = ''
        Seed color in hex format (e.g., "#ff0000") to generate the palette from.
        Mutually exclusive with `wallpaper`.
      '';
    };

    mode = lib.mkOption {
      type = lib.types.enum [
        "dark"
        "light"
      ];
      default = "dark";
      description = ''
        Color scheme mode. This determines which variant (dark or light) 
        will be assigned to the `default` field in the generated colors.
      '';
    };

    scheme = lib.mkOption {
      type = lib.types.enum [
        "content"
        "expressive"
        "fidelity"
        "fruit-salad"
        "monochrome"
        "neutral"
        "rainbow"
        "tonal-spot"
        "vibrant"
      ];
      default = "tonal-spot";
      description = "Matugen generation scheme to use.";
    };

    customColors = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      example = lib.literalExpression ''
        {
          myColor = "#ff0000";
          terminal = {
            black = "#000000";
          };
        }
      '';
      description = ''
        Custom colors or color sets to include in the module output.
        These are stored in `config.matugen.theme.custom`.
      '';
    };

    theme = lib.mkOption {
      type = lib.types.submodule {
        options = {
          generated = lib.mkOption {
            type = lib.types.attrsOf lib.types.anything;
            readOnly = true;
            description = "The data generated by matugen (colors, base16, palettes).";
          };
          custom = lib.mkOption {
            type = lib.types.attrsOf lib.types.anything;
            readOnly = true;
            description = "User-provided custom colors.";
          };
        };
      };
      readOnly = true;
      default = theme;
      description = "The final resolved theme structure.";
    };
  };
  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.wallpaper != null || cfg.seedColor != null;
        message = "matugen: You must specify either `wallpaper` or `seedColor`.";
      }
      {
        assertion = !(cfg.wallpaper != null && cfg.seedColor != null);
        message = "matugen: `wallpaper` and `seedColor` cannot be used together.";
      }
    ];
  };
}
