{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.matugen;

  matugenJson = pkgs.runCommand "matugen-colors.json" {
    WALLPAPER = if cfg.wallpaper != null then cfg.wallpaper else "";
    SEED = if cfg.seedColor != null then cfg.seedColor else "";
  } ''
    if [ -n "$WALLPAPER" ]; then
      ${pkgs.matugen}/bin/matugen image "$WALLPAPER" \
        -j hex \
        -m ${cfg.mode} \
        -t scheme-${cfg.scheme} \
        --contrast ${toString cfg.contrast} \
        --prefer ${cfg.prefer} > $out
    elif [ -n "$SEED" ]; then
      ${pkgs.matugen}/bin/matugen color hex "$SEED" \
        -j hex \
        -m ${cfg.mode} \
        -t scheme-${cfg.scheme} > $out
    else
      echo "{}" > $out
    fi
  '';

  generatedTheme =
    if cfg.enable then
      builtins.fromJSON (builtins.unsafeDiscardStringContext (builtins.readFile matugenJson))
    else
      {
        colors = {
          dark = { };
          light = { };
        };
      };

  parseColorObject =
    obj:
    if builtins.isAttrs obj && builtins.hasAttr "color" obj then
      obj.color
    else if builtins.isAttrs obj then
      builtins.mapAttrs (n: v: parseColorObject v) obj
    else
      obj;

  parsedColors = parseColorObject (generatedTheme.colors or { });
  parsedBase16 = parseColorObject (generatedTheme.base16 or { });

  parsedPalettes = builtins.mapAttrs (
    name: tones: builtins.mapAttrs (tone: value: value.color or "") tones
  ) (generatedTheme.palettes or { });

  theme = {
    generated = {
      colors = parsedColors;
      base16 = parsedBase16;
      palettes = parsedPalettes;
    };
    custom = cfg.customColors;
  };
in
{
  options.matugen = {
    enable = lib.mkEnableOption "Matugen color generation module";

    wallpaper = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = lib.literalExpression "./wallpapers/image.png";
      description = ''
        Path to the wallpaper image to use as the base for the color palette.
        Mutually exclusive with `seedColor`.
      '';
    };

    seedColor = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "#ff0000";
      description = ''
        Seed color in hex format (e.g., "#ff0000") to generate the palette from.
        Mutually exclusive with `wallpaper`.
      '';
    };

    mode = lib.mkOption {
      type = lib.types.enum [
        "dark"
        "light"
      ];
      default = "dark";
      description = ''
        Color scheme mode. This determines which variant (dark or light) 
        will be assigned to the `default` field in the generated colors.
      '';
    };

    scheme = lib.mkOption {
      type = lib.types.enum [
        "content"
        "expressive"
        "fidelity"
        "fruit-salad"
        "monochrome"
        "neutral"
        "rainbow"
        "tonal-spot"
        "vibrant"
      ];
      default = "tonal-spot";
      description = "Matugen generation scheme to use.";
    };

    prefer = lib.mkOption {
      type = lib.types.enum [
        "darkness"
        "lightness"
        "saturation"
        "less-saturation"
        "value"
        "closest-to-fallback"
      ];
      default = "saturation";
      description = ''
        When multiple colors can be extracted from an image, this decides 
        which to pick without needing user input. (Only applies when using `wallpaper`).
      '';
    };

    contrast = lib.mkOption {
      type = lib.types.nullOr lib.types.float;
      default = 0.0;
      example = 0.5;
      description = ''
        The contrast level to pass to Matugen. 
        Usually ranges from -1.0 to 1.0. If null, the default contrast (0.0) is used.
      '';
    };

    customColors = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      example = lib.literalExpression ''
        {
          myColor = "#ff0000";
          terminal = {
            black = "#000000";
          };
        }
      '';
      description = ''
        Custom colors or color sets to include in the module output.
        These are stored in `config.matugen.theme.custom`.
      '';
    };

    theme = lib.mkOption {
      type = lib.types.submodule {
        options = {
          generated = lib.mkOption {
            type = lib.types.attrsOf lib.types.anything;
            readOnly = true;
            description = "The data generated by matugen (colors, base16, palettes).";
          };
          custom = lib.mkOption {
            type = lib.types.attrsOf lib.types.anything;
            readOnly = true;
            description = "User-provided custom colors.";
          };
        };
      };
      readOnly = true;
      default = theme;
      description = "The final resolved theme structure.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.wallpaper != null || cfg.seedColor != null;
        message = "matugen: You must specify either `wallpaper` or `seedColor`.";
      }
      {
        assertion = !(cfg.wallpaper != null && cfg.seedColor != null);
        message = "matugen: `wallpaper` and `seedColor` cannot be used together.";
      }
    ];
  };
}
